---
title: "Figures"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## For figures - 230505

```{r}
myfolder <- "/Users/juliafoyer/ST/HDCA_heart/single_cell/results/figure_images/"
```

```{r}
subset <- readRDS("/Users/juliafoyer/ST/HDCA_heart/single_cell/results/HDCA_heart_sc_analysis_it8/rds_objects/HDCA_heart_sc_subset_endothelial.rds")
```

```{r}
pdf(file = paste0(myfolder, "Endothelial_clusters.pdf"), width = 15, height = 15, bg = "transparent")
DimPlot(object = subset, reduction = "umap_subset", group.by = "clusters_subset", raster = F, pt.size = 1) + NoLegend()
dev.off()

pdf(file = paste0(myfolder, "Endothelial_clusters_with_numbers.pdf"), width = 15, height = 15, bg = "transparent")
DimPlot(object = subset, reduction = "umap_subset", group.by = "clusters_subset", raster = F, pt.size = 1, label = T)
dev.off()

pdf(file = paste0(myfolder, "Endothelial_clusters_with_legend.pdf"), width = 15, height = 15, bg = "transparent")
DimPlot(object = subset, reduction = "umap_subset", group.by = "clusters_subset", raster = F, pt.size = 1, label = F)
dev.off()
```

```{r}
subset <- readRDS("/Users/juliafoyer/ST/HDCA_heart/single_cell/results/HDCA_heart_sc_analysis_it8/rds_objects/HDCA_heart_sc_subset_fibroblasts.rds")
```

```{r}
pdf(file = paste0(myfolder, "Fibroblast_clusters.pdf"), width = 15, height = 15, bg = "transparent")
DimPlot(object = subset, reduction = "umap_subset", group.by = "clusters_subset", raster = F, pt.size = 1) + NoLegend()
dev.off()

pdf(file = paste0(myfolder, "Fibroblast_clusters_with_numbers.pdf"), width = 15, height = 15, bg = "transparent")
DimPlot(object = subset, reduction = "umap_subset", group.by = "clusters_subset", raster = F, pt.size = 1, label = T)
dev.off()

pdf(file = paste0(myfolder, "Fibroblast_clusters_with_legend.pdf"), width = 15, height = 15, bg = "transparent")
DimPlot(object = subset, reduction = "umap_subset", group.by = "clusters_subset", raster = F, pt.size = 1, label = F)
dev.off()
```

```{r}
data <- readRDS(paste0(myfolder, "rds_objects/HDCA_heart_sc_full.rds"))
```

```{r}
pdf(file = paste0(myfolder, "Clusters_modified.pdf"), width = 15, height = 15, bg = "transparent")
DimPlot(data, reduction = "umap_oi", group.by = "clusters_louvain_oi", raster = F, pt.size = 1)
dev.off()

pdf(file = paste0(myfolder, "Clusters_modified_with_numbers.pdf"), width = 15, height = 15, bg = "transparent")
DimPlot(data, reduction = "umap_oi", group.by = "clusters_louvain_oi", raster = F, label = T, pt.size = 1)
dev.off()

pdf(file = paste0(myfolder, "Annotation_modified.pdf"), width = 15, height = 15, bg = "transparent")
DimPlot(data, reduction = "umap_oi", group.by = "cell.types", raster = F, pt.size = 1)
dev.off()
```

```{r}
subset <- readRDS(paste0(myfolder, "rds_objects/HDCA_heart_sc_subset_cardiomyocytes_extended.rds"))
```

```{r}
pdf(file = paste0(myfolder, "Cardiomyocyte_clusters.pdf"), width = 15, height = 15, bg = "transparent")
DimPlot(object = subset, reduction = "umap_subset", group.by = "clusters_subset", raster = F, pt.size = 1) + NoLegend()
dev.off()

pdf(file = paste0(myfolder, "Cardiomyocyte_clusters_with_numbers.pdf"), width = 15, height = 15, bg = "transparent")
DimPlot(object = subset, reduction = "umap_subset", group.by = "clusters_subset", raster = F, pt.size = 1, label = T)
dev.off()

pdf(file = paste0(myfolder, "Cardiomyocyte_clusters_with_legend.pdf"), width = 15, height = 15, bg = "transparent")
DimPlot(object = subset, reduction = "umap_subset", group.by = "clusters_subset", raster = F, pt.size = 1, label = F)
dev.off()
```

## Combining annotation levels

```{r}
data <- readRDS(paste0(myfolder, "rds_objects/HDCA_heart_sc_full.rds"))
CMs <- readRDS(paste0(myfolder, "rds_objects/HDCA_heart_sc_subset_cardiomyocytes_extended.rds"))
FBs <- readRDS(paste0(myfolder, "rds_objects/HDCA_heart_sc_subset_fibroblasts.rds"))
ECs <- readRDS(paste0(myfolder, "rds_objects/HDCA_heart_sc_subset_endothelial.rds"))
```

```{r}
CM_index <- match(colnames(CMs), colnames(data))
CM_clusters <- CMs@meta.data$clusters_subset

E_index <- match(colnames(ECs), colnames(data))
E_clusters <- ECs@meta.data$clusters_subset

F_index <- match(colnames(FBs), colnames(data))
F_clusters <- FBs@meta.data$clusters_subset
```

```{r}
df <- data.frame(matrix(ncol = 2, nrow = length(colnames(data))))
colnames(df) <- c("high_level_cluster", "deep_level_cluster")
df$high_level_cluster <- data@meta.data$high_level_clusters
```

```{r}
for (i in 1:length(CM_index)){
  ind <- CM_index[i]
  # df$CM_cluster[ind] <- CM_clusters[i]
  df$deep_level_cluster[ind] <- paste0("Cardiomyocyte_cl_", CM_clusters[i])
}

for (i in 1:length(E_index)){
  ind <- E_index[i]
  # df$E_cluster[ind] <- E_clusters[i]
  df$deep_level_cluster[ind] <- paste0("Endothelial_cl_", E_clusters[i])
}

for (i in 1:length(F_index)){
  ind <- F_index[i]
  # df$F_cluster[ind] <- F_clusters[i]
  df$deep_level_cluster[ind] <- paste0("Fibroblast_cl_", F_clusters[i])
}

df$deep_level_cluster <- ifelse(is.na(df$deep_level_cluster), paste0("High_level_cl_", df$high_level_cluster), df$deep_level_cluster)
```

```{r}
data$deep_level_clusters <- df$deep_level_cluster
table(data$deep_level_clusters)
```

```{r}
saveRDS(data, paste0(myfolder, "rds_objects/HDCA_heart_sc_deep_level_clustering.rds"))
```
