---
title: "14_HDCA_heart_pathological_enrichment"
author: "Raphaël Mauron"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
.libPaths("/home/rstudio/project/renv/library/R-4.3/aarch64-unknown-linux-gnu/")
knitr::opts_chunk$set(echo = TRUE)
```


## Set environment variables

```{r}
# Set the directory 
myfolder <- "/home/rstudio/project/output/HDCA_heart_sc_analysis_docker/"
```


## Load Seurat object

```{r, message = FALSE}
data <- readRDS(paste0(myfolder, "rds_objects/HDCA_heart_sc_full_extended.rds"))
CM <- readRDS(file = paste0(myfolder, "rds_objects/cardiomyocytes02.rds"))
EN <- readRDS(file = paste0(myfolder, "rds_objects/endothelial.rds"))
FB <- readRDS(paste0(myfolder, "rds_objects/fibroblasts.rds"))
```


## Load libraries

```{r, message = FALSE}
library(Seurat)
library(Matrix)
library(dplyr)
library(data.table)
library(tibble)
library(openxlsx)
library(patchwork)
```



### Gene Set Enrichment Analysis (GSEA) between pathological database and high level clusters

#### Load DATABASE chdgene_filtered_by_malformation_230116

```{r}
# DEG calculated only between ST clusters in the heart subset 
chdgene <- read.xlsx("/home/rstudio/project/data/patho_db/chdgene_filtered_by_malformation_230116.xlsx",
                                 sheet='chdgene_transposed', colNames = FALSE, rowNames = TRUE)

# Create list from the pathological database
chdgene <- lapply(split(chdgene, row.names(chdgene)), function(x) as.character(x[-ncol(x)]))
```


#### For CM/chdgene

```{r}
# Subset CM clusters of interest
subset_values <- c("1", "2", "3", "4-1", "4-2", "5", "6", "7", "8-1", "8-2", "8-3", "9", "10", "12", "14", "17", "18", "19-1", "19-2", "21")
CM_subset <- CM[, CM$clusters_subset_split %in% subset_values]

# reorder the cell types desired
CM_subset$clusters_subset_split <- factor(CM_subset$clusters_subset_split, levels = c("6", "1", "10", "8-1", "8-3", "17", "8-2", "18", "4-2", "4-1", "3", "14", "9", "12", "21", "19-2", "19-1", "7", "2", "5"))


# Compute module score on single-cell data
CM_subset <- AddModuleScore(CM_subset, features = chdgene, name = "Patho_enrich")


# Get list name to change the column names in meta.data
# Rename the Enrichment_Score meta.data
# Create new_column_names using the list of numbers
name_list <- names(chdgene)
new_column_names <- paste("Patho_enrich_", name_list, sep = "")
for (i in 32:41) {
  colnames(CM_subset@meta.data)[i] <- new_column_names[i - 31]
}


pdf(file = paste0(myfolder, "patho_enrich/Violin_CM_chdgene.pdf"), 
     width = 20, height = 20)
VlnPlot(CM_subset, features = new_column_names, group.by = "clusters_subset_split") + 
  plot_layout(ncol = 2)
dev.off()
```


#### For EN/chdgene

```{r}
# Subset EN clusters of interest
subset_values <- c("1", "12", "3", "6", "18", "17", "7", "19", "15", "13", "10", "2", "5", "21", "16", "20", "11", "14", "22")
EN_subset <- EN[, EN$clusters_subset %in% subset_values]

# reorder the cell types desired
EN_subset$clusters_subset <- factor(EN_subset$clusters_subset, levels = c("1", "12", "3", "6", "18", "17", "7", "19", "15", "13", "10", "2", "5", "21", "16", "20", "11", "14", "22"))


# Compute module score on single-cell data
EN_subset <- AddModuleScore(EN_subset, features = chdgene, name = "Patho_enrich")


# Get list name to change the column names in meta.data
# Rename the Enrichment_Score meta.data
# Create new_column_names using the list of numbers
name_list <- names(chdgene)
new_column_names <- paste("Patho_enrich_", name_list, sep = "")
for (i in 31:40) {
  colnames(EN_subset@meta.data)[i] <- new_column_names[i - 30]
}


pdf(file = paste0(myfolder, "patho_enrich/Violin_EN_chdgene.pdf"), 
     width = 20, height = 20)
VlnPlot(EN_subset, features = new_column_names, group.by = "clusters_subset") + 
  plot_layout(ncol = 2)
dev.off()
```


#### For FB/chdgene

```{r}
# Subset FB clusters of interest
subset_values <- c("7", "3", "18", "14", "5", "9", "19", "2", "12", "4", "13", "11", "17", "8", "1", "6", "15", "20", "21")
FB_subset <- FB[, FB$clusters_subset %in% subset_values]

# reorder the cell types desired
FB_subset$clusters_subset <- factor(FB_subset$clusters_subset, levels = c("7", "3", "18", "14", "5", "9", "19", "2", "12", "4", "13", "11", "17", "8", "1", "6", "15", "20", "21"))


# Compute module score on single-cell data
FB_subset <- AddModuleScore(FB_subset, features = chdgene, name = "Patho_enrich")


# Get list name to change the column names in meta.data
# Rename the Enrichment_Score meta.data
# Create new_column_names using the list of numbers
name_list <- names(chdgene)
new_column_names <- paste("Patho_enrich_", name_list, sep = "")
for (i in 31:40) {
  colnames(FB_subset@meta.data)[i] <- new_column_names[i - 30]
}


pdf(file = paste0(myfolder, "patho_enrich/Violin_FB_chdgene.pdf"), 
     width = 20, height = 20)
VlnPlot(FB_subset, features = new_column_names, group.by = "clusters_subset") + 
  plot_layout(ncol = 2)
dev.off()
```

#### For CM+EN+FB/chdgene

```{r}
# Subset CM clusters of interest (exclude:  11, 13, 15, 16, 20, 22)
subset_values <- c("1", "2", "3", "4-1", "4-2", "5", "6", "7", "8-1", "8-2", "8-3", "9", "10", "12", "14", "17", "18", "19-1", "19-2", "21")
CM_subset <- CM[, CM$clusters_subset_split %in% subset_values]
# reorder the cell types desired
CM_subset$clusters_subset_split <- factor(CM_subset$clusters_subset_split, levels = c("6", "1", "10", "8-1", "8-3", "17", "8-2", "18", "4-2", "4-1", "3", "14", "9", "12", "21", "19-2", "19-1", "7", "2", "5"))
rm(CM)
gc()

# Subset EN clusters of interest (exclude:  11, 13, 15, 16, 20, 22)
subset_values <- c("1", "12", "3", "6", "18", "17", "7", "19", "15", "13", "10", "2", "5", "21", "16", "20", "11", "14", "22")
EN_subset <- EN[, EN$clusters_subset %in% subset_values]
# reorder the cell types desired
EN_subset$clusters_subset <- factor(EN_subset$clusters_subset, levels = c("1", "12", "3", "6", "18", "17", "7", "19", "15", "13", "10", "2", "5", "21", "16", "20", "11", "14", "22"))
rm(EN)
gc()

# Subset FB clusters of interest
subset_values <- c("7", "3", "18", "14", "5", "9", "19", "2", "12", "4", "13", "11", "17", "8", "1", "6", "15", "20", "21")
FB_subset <- FB[, FB$clusters_subset %in% subset_values]

# reorder the cell types desired
FB_subset$clusters_subset <- factor(FB_subset$clusters_subset, levels = c("7", "3", "18", "14", "5", "9", "19", "2", "12", "4", "13", "11", "17", "8", "1", "6", "15", "20", "21"))
rm(FB)
gc()

# Subset HL clsuters of interest
subset_values <- c("6", "8", "10", "15", "18_1", "20", "22", "25", "26", "29", "34")
HL_subset <- data[, data$high_level_clusters %in% subset_values]

# reorder the cell types desired
HL_subset$high_level_clusters <- factor(HL_subset$high_level_clusters, levels = c("6", "8", "10", "15", "18_1", "20", "22", "25", "26", "29", "34"))
rm(data)
gc()

# Create a similarly named meta.data row for each object
CM_subset$final_clusters <- paste0("CM_", CM_subset$clusters_subset_split)
EN_subset$final_clusters <- paste0("EN_", EN_subset$clusters_subset)
FB_subset$final_clusters <- paste0("FB_", FB_subset$clusters_subset)
HL_subset$final_clusters <- paste0("HL_", HL_subset$high_level_clusters)


# Merge the objects and keep the factor level of each of the object
Merged_object <- merge(CM_subset, y = c(EN_subset, FB_subset, HL_subset))

Merged_object$final_clusters <- factor(Merged_object$final_clusters, 
                               levels = c(paste0("CM_", levels(CM_subset$clusters_subset_split)),
                                          paste0("EN_", levels(EN_subset$clusters_subset)),
                                          paste0("FB_", levels(FB_subset$clusters_subset)),
                                          paste0("HL_", levels(HL_subset$high_level_clusters))))

rm(CM_subset, EN_subset, FB_subset, HL_subset)
gc()

# Compute module score on single-cell data
Merged_object <- AddModuleScore(Merged_object, features = chdgene, name = "Patho_enrich")


# Get list name to change the column names in meta.data
# Rename the Enrichment_Score meta.data
# Create new_column_names using the list of numbers
name_list <- names(chdgene)
new_column_names <- paste("Patho_enrich_", name_list, sep = "")
for (i in 33:42) {
  colnames(Merged_object@meta.data)[i] <- new_column_names[i - 32]
}

# Plot patchwork for every pathology
pdf(file = paste0(myfolder, "patho_enrich/Violin_merged_chdgene.pdf"), 
     width = 20, height = 20)
VlnPlot(Merged_object, features = new_column_names, group.by = "final_clusters", pt.size = 0) + 
  plot_layout(ncol = 2)
dev.off()

# Plot new figures for each pathology
for (condition in new_column_names) {
  p <- VlnPlot(Merged_object, features = condition, group.by = "final_clusters", pt.size = 0)
  pdf(file = paste0(myfolder, "patho_enrich/Violin_merged_chdgene_", condition, ".pdf"), width = 20, height = 5)
  print(p + theme(legend.position = "none"))
  dev.off()
}
```


================================================================================
================================================================================
================================================================================
================================================================================
================================================================================






